import mongoose from 'mongoose';

/* ── WpClient ──────────────────────────────────────────────────────────────
   One record per client/workspace. Each has a unique PIN for access.
   Designed so future clients can be added with their own PIN + workspace.
────────────────────────────────────────────────────────────────────────── */
const wpClientSchema = new mongoose.Schema({
  slug:   { type: String, required: true, unique: true },
  name:   { type: String, required: true },
  pin:    { type: String, required: true },
  active: { type: Boolean, default: true },
  workspace: {
    businessName: { type: String, default: '' },
    businessType: { type: String, default: '' },
    industry:     { type: String, default: '' },
    timezone:     { type: String, default: 'Asia/Kolkata' },
  },
  createdAt: { type: Date, default: Date.now },
});

/* ── WpContactList ─────────────────────────────────────────────────────────
   A named list of contacts belonging to a client. Contacts carry optional
   enrichment data (order count, spend, last order) pulled from Picoso orders.
────────────────────────────────────────────────────────────────────────── */
const wpContactSchema = new mongoose.Schema({
  name:          { type: String, default: '' },
  phone:         { type: String, required: true },
  email:         { type: String, default: '' },
  tags:          [{ type: String }],
  notes:         { type: String, default: '' },
  customFields:  { type: mongoose.Schema.Types.Mixed, default: {} },
  orderCount:    { type: Number, default: 0 },
  totalSpend:    { type: Number, default: 0 },
  lastOrderDate: { type: Date, default: null },
}, { _id: true });

const wpContactListSchema = new mongoose.Schema({
  clientId:    { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient', required: true },
  name:        { type: String, required: true },
  description: { type: String, default: '' },
  contacts:    [wpContactSchema],
  createdAt:   { type: Date, default: Date.now },
  updatedAt:   { type: Date, default: Date.now },
});

/* ── WpCampaignDraft ───────────────────────────────────────────────────────
   Holds a campaign as it moves through the creation flow. The `aiStrategy`
   field is populated once the user completes Step 2 and AI analysis runs.
────────────────────────────────────────────────────────────────────────── */
const campaignStrategySchema = new mongoose.Schema({
  objective:         String,
  audience:          String,
  tone:              String,
  keyMessages:       [String],
  callToAction:      String,
  timing:            String,
  suggestedTemplate: String,
  reasoning:         String,
}, { _id: false });

const wpCampaignDraftSchema = new mongoose.Schema({
  clientId:      { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient', required: true },
  name:          { type: String, default: 'Untitled Campaign' },
  status: {
    type: String,
    enum: ['draft', 'strategy_ready', 'scheduled', 'running', 'completed', 'paused'],
    default: 'draft',
  },
  contactListId: { type: mongoose.Schema.Types.ObjectId, ref: 'WpContactList', default: null },
  context:       { type: String, default: '' },
  aiStrategy:    { type: campaignStrategySchema, default: null },
  createdAt:     { type: Date, default: Date.now },
  updatedAt:     { type: Date, default: Date.now },
});

/* ── WpExperiment ──────────────────────────────────────────────────────────
   Holds the full multi-phase A/B experiment plan generated by AI for a
   campaign. Status moves: awaiting_approval → approved → running → completed.
   Nothing is sent until the client explicitly approves the plan.
────────────────────────────────────────────────────────────────────────── */
const wpPhaseSchema = new mongoose.Schema({
  phaseNumber:       { type: Number, required: true },   // 1, 2, 3, 4
  label:             { type: String, required: true },   // "Phase 1: 10 Variants"
  variantCount:      { type: Number, required: true },   // 10, 5, 3, 1
  contactsPerVariant:{ type: Number, required: true },
  totalContacts:     { type: Number, required: true },
  rounds:            { type: Number, default: 3 },
  daySpread:         { type: Number, default: 6 },
  scheduledDates:    [{ type: Date }],
  defaultSendTime:   { type: String, default: '10:00' }, // HH:mm, used for scheduling
  status: { type: String, enum: ['pending', 'running', 'completed'], default: 'pending' },
  approvedAt: { type: Date, default: null },
  startedAt:  { type: Date, default: null },
}, { _id: false });

const wpVariantMetricsSchema = new mongoose.Schema({
  sent:              { type: Number, default: 0 },
  delivered:         { type: Number, default: 0 },
  read:              { type: Number, default: 0 },
  linkClicks:        { type: Number, default: 0 },
  uniqueLinkClicks:  { type: Number, default: 0 },
  repeatClicks:      { type: Number, default: 0 },
  replies:           { type: Number, default: 0 },
  conversions:       { type: Number, default: 0 },
  revenue:           { type: Number, default: 0 },
}, { _id: false });

const wpVariantButtonSchema = new mongoose.Schema({
  type: { type: String, enum: ['URL', 'QUICK_REPLY', 'PHONE'], default: 'URL' },
  text: { type: String, default: '' },
  url:  { type: String, default: '' },
  phone:{ type: String, default: '' },
}, { _id: false });

const wpVariantSchema = new mongoose.Schema({
  variantNumber:           { type: Number, required: true },  // 1–10
  label:                   { type: String, required: true },  // "Variant A"
  copyAngle:               { type: String, default: '' },
  tone:                    { type: String, default: '' },
  offer:                   { type: String, default: '' },
  cta:                     { type: String, default: '' },
  imageConceptDescription: { type: String, default: '' },
  message:                 { type: String, default: '' }, // legacy alias of body
  // WhatsApp template structure (Create Template form)
  templateName:            { type: String, default: '' },
  category:                { type: String, enum: ['MARKETING', 'UTILITY', 'AUTHENTICATION'], default: 'MARKETING' },
  language:                { type: String, default: 'en_US' },
  headerType:              { type: String, enum: ['NONE', 'TEXT', 'IMAGE', 'VIDEO', 'DOCUMENT'], default: 'NONE' },
  headerText:              { type: String, default: '' },
  body:                    { type: String, default: '' },
  footerType:              { type: String, enum: ['NONE', 'TEXT', 'BUTTONS'], default: 'NONE' },
  footerText:              { type: String, default: '' },
  buttons:                 [wpVariantButtonSchema],
  variableExamples:        { type: mongoose.Schema.Types.Mixed, default: () => ({ 1: 'Rahul' }) },
  mediaS3Url:              { type: String, default: '' },
  mediaWaId:               { type: String, default: '' },
  imageGenStatus:          { type: String, enum: ['pending', 'generating', 'ready', 'failed'], default: 'pending' },
  imageGenError:           { type: String, default: '' },
  scheduledSendTime:       { type: String, default: '10:00' }, // HH:mm, editable per variant
  waPublishStatus:         { type: String, enum: ['draft', 'queued', 'publishing', 'published', 'failed'], default: 'draft' },
  waPublishError:          { type: String, default: '' },
  waPublishedAt:           { type: Date, default: null },
  status: {
    type: String,
    enum: ['active', 'top5', 'top3', 'winner', 'eliminated'],
    default: 'active',
  },
  phaseEliminated: { type: Number, default: null },
  metrics: { type: wpVariantMetricsSchema, default: () => ({}) },
}, { _id: true });

const wpExperimentSchema = new mongoose.Schema({
  clientId:      { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient',       required: true },
  campaignId:    { type: mongoose.Schema.Types.ObjectId, ref: 'WpCampaignDraft', required: true },
  contactListId: { type: mongoose.Schema.Types.ObjectId, ref: 'WpContactList',  required: true },
  context:       { type: String, default: '' },
  status: {
    type: String,
    enum: ['awaiting_approval', 'approved', 'running', 'paused', 'completed'],
    default: 'awaiting_approval',
  },
  plan: {
    totalAudience:      { type: Number, default: 0 },
    experimentTitle:    { type: String, default: '' },
    objective:          { type: String, default: '' },
    reasoning:          { type: String, default: '' },
    trackingEnabled:    { type: Boolean, default: true },
    trackingExplanation:{ type: String, default: '' },
    phases:             [wpPhaseSchema],
    optimizationCriteria: {
      primaryMetric:    { type: String, default: 'conversions' },
      signals:          [{ type: String }],
      progressionLogic: { type: String, default: '' },
    },
    templateConfig: {
      templateId:      { type: String, default: '' },
      templateName:    { type: String, default: '' },
      languageCode:    { type: String, default: 'en_US' },
      hasUrlButton:    { type: Boolean, default: false },
      destinationUrl:  { type: String, default: 'https://picoso.in' },
    },
  },
  variants:    [wpVariantSchema],
  approvedAt:  { type: Date, default: null },
  createdAt:   { type: Date, default: Date.now },
  updatedAt:   { type: Date, default: Date.now },
});

/* ── WpTrackingLink ────────────────────────────────────────────────────────
   One record per (contact × variant × campaign). Each WhatsApp message
   carries a unique short-code link so clicks are attributed back to the
   exact customer, variant and experiment.
────────────────────────────────────────────────────────────────────────── */
const wpTrackingLinkSchema = new mongoose.Schema({
  shortCode:    { type: String, required: true, unique: true },
  clientId:     { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient' },
  experimentId: { type: mongoose.Schema.Types.ObjectId, ref: 'WpExperiment' },
  variantNumber:{ type: Number },
  contactPhone: { type: String, default: '' },
  contactName:  { type: String, default: '' },
  originalUrl:  { type: String, required: true },
  clicks: [{
    clickedAt: { type: Date, default: Date.now },
    isRepeat:  { type: Boolean, default: false },
    userAgent: { type: String, default: '' },
    ip:        { type: String, default: '' },
  }],
  converted:          { type: Boolean, default: false },
  conversionOrderId:  { type: String, default: null },
  conversionValue:    { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

/* ── WpCampaignRun ─────────────────────────────────────────────────────────
   One record per execution cycle (e.g. Phase 1 Run 2). Tracks which variants
   ran, aggregate delivery stats, and the AI-generated post-run analysis.
────────────────────────────────────────────────────────────────────────── */
const wpRunMetricsSchema = new mongoose.Schema({
  sent:         { type: Number, default: 0 },
  delivered:    { type: Number, default: 0 },
  read:         { type: Number, default: 0 },
  clicks:       { type: Number, default: 0 },
  uniqueClicks: { type: Number, default: 0 },
  replies:      { type: Number, default: 0 },
  conversions:  { type: Number, default: 0 },
  revenue:      { type: Number, default: 0 },
}, { _id: false });

const wpRunAiAnalysisSchema = new mongoose.Schema({
  summary:             { type: String, default: '' },
  variantRankings:     [{ variantNumber: Number, label: String, score: Number, reason: String }],
  advancementDecision: { type: String, default: '' },
  advancedVariants:    [Number],
  eliminatedVariants:  [Number],
  generatedAt:         { type: Date, default: null },
}, { _id: false });

const wpCampaignRunSchema = new mongoose.Schema({
  clientId:       { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient',    required: true },
  experimentId:   { type: mongoose.Schema.Types.ObjectId, ref: 'WpExperiment', required: true },
  phaseNumber:    { type: Number, required: true },
  runNumber:      { type: Number, required: true },
  status: {
    type: String,
    enum: ['pending', 'running', 'completed', 'failed', 'analyzed'],
    default: 'pending',
  },
  variantNumbers:     [{ type: Number }],
  contactCount:       { type: Number, default: 0 },
  campaignBotRefId:   { type: String, default: null },
  scheduledAt:        { type: Date, default: null },
  startedAt:          { type: Date, default: null },
  completedAt:        { type: Date, default: null },
  metrics:            { type: wpRunMetricsSchema, default: () => ({}) },
  aiAnalysis:         { type: wpRunAiAnalysisSchema, default: null },
  createdAt:          { type: Date, default: Date.now },
});

/* ── WpMessageLog ──────────────────────────────────────────────────────────
   Per-message record. Connects every outbound message to the exact contact,
   variant, and run. Updated in real time as delivery webhooks arrive.
────────────────────────────────────────────────────────────────────────── */
const wpMessageLogSchema = new mongoose.Schema({
  clientId:         { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient' },
  experimentId:     { type: mongoose.Schema.Types.ObjectId, ref: 'WpExperiment' },
  campaignRunId:    { type: mongoose.Schema.Types.ObjectId, ref: 'WpCampaignRun' },
  variantNumber:    { type: Number },
  phaseNumber:      { type: Number },
  runNumber:        { type: Number },
  contactPhone:     { type: String, default: '' },
  contactName:      { type: String, default: '' },
  wamid:            { type: String, default: null, index: true }, // WhatsApp message ID
  campaignBotRefId: { type: String, default: null },
  templateName:     { type: String, default: '' },
  status: {
    type: String,
    enum: ['queued', 'sent', 'delivered', 'read', 'failed'],
    default: 'queued',
    index: true,
  },
  sentAt:       { type: Date, default: null },
  deliveredAt:  { type: Date, default: null },
  readAt:       { type: Date, default: null },
  failedAt:     { type: Date, default: null },
  failureTitle: { type: String, default: null },
  failureMsg:   { type: String, default: null },
  // Tracking link
  trackingShortCode: { type: String, default: null },
  trackingUrl:       { type: String, default: null },
  // Engagement
  clicked:      { type: Boolean, default: false },
  totalClicks:  { type: Number, default: 0 },
  firstClickAt: { type: Date, default: null },
  replied:      { type: Boolean, default: false },
  // Conversion
  converted:          { type: Boolean, default: false },
  conversionOrderId:  { type: String, default: null },
  conversionValue:    { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

/* ── WpScheduledJob ────────────────────────────────────────────────────────
   One record per run within a phase. Created when a phase is started via the
   "one-click" flow. Pending jobs are picked up by the background scheduler
   and executed when scheduledAt <= now.
────────────────────────────────────────────────────────────────────────── */
const wpScheduledJobSchema = new mongoose.Schema({
  clientId:     { type: mongoose.Schema.Types.ObjectId, ref: 'WpClient',     required: true },
  experimentId: { type: mongoose.Schema.Types.ObjectId, ref: 'WpExperiment', required: true },
  phaseNumber:  { type: Number, required: true },
  phaseIndex:   { type: Number, required: true },
  runNumber:    { type: Number, required: true },
  scheduledAt:  { type: Date, required: true },
  status: {
    type: String,
    enum: ['pending', 'running', 'completed', 'failed', 'cancelled'],
    default: 'pending',
  },
  executedAt: { type: Date, default: null },
  runId:      { type: mongoose.Schema.Types.ObjectId, ref: 'WpCampaignRun', default: null },
  error:      { type: String, default: null },
  templateConfig: {
    templateId:     { type: String, default: '' },
    templateName:   { type: String, default: '' },
    languageCode:   { type: String, default: 'en_US' },
    hasUrlButton:   { type: Boolean, default: false },
    destinationUrl: { type: String, default: 'https://picoso.in' },
  },
  createdAt: { type: Date, default: Date.now },
});

export const WpClient         = mongoose.models.WpClient         || mongoose.model('WpClient',         wpClientSchema);
export const WpContactList    = mongoose.models.WpContactList    || mongoose.model('WpContactList',    wpContactListSchema);
export const WpCampaignDraft  = mongoose.models.WpCampaignDraft  || mongoose.model('WpCampaignDraft',  wpCampaignDraftSchema);
export const WpExperiment     = mongoose.models.WpExperiment     || mongoose.model('WpExperiment',     wpExperimentSchema);
export const WpTrackingLink   = mongoose.models.WpTrackingLink   || mongoose.model('WpTrackingLink',   wpTrackingLinkSchema);
export const WpCampaignRun    = mongoose.models.WpCampaignRun    || mongoose.model('WpCampaignRun',    wpCampaignRunSchema);
export const WpMessageLog     = mongoose.models.WpMessageLog     || mongoose.model('WpMessageLog',     wpMessageLogSchema);
export const WpScheduledJob   = mongoose.models.WpScheduledJob   || mongoose.model('WpScheduledJob',   wpScheduledJobSchema);
